# Site
name: "Jaywick Gazette"
title: "Jaywick Gazette"
description: "Welcome to Jaywick Gazette, your trusted news outlet bringing you reliable and engaging stories from Jaywick and Essex."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: 'G-M0JL6R5HNJ'
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  mike:
    name: Michael McHeath
    display_name: Micheal McHeath
    gravatar: f0e843e762852eb7c0a509e1a6f405a0
    email: mike.mcheath@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/mike
    twitter: https://twitter.com/mikemcheathJG
    description: "Michael has stood at the forefront of Essex's dynamic news scene. His interests span art, sculpture, and music, with Dire Straits being his favorite band. Having spent the last two decades in Jaywick, he weaves his unique experiences into his articles, creating rich, vibrant narratives. His work continues to shape and define the cultural conversation."
  wayne:
    name: Wayne Sanders
    display_name: Wayne Sanders
    gravatar: 99f9ec241c4a6c0895a44e83e37e9b7b
    email: wayne.sanders@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/wayne
    twitter: https://twitter.com/waynesandersJG
    description: "Originally from Jaywick, Wayne loves banter and pints with mates at local pubs. He's a Brexit supporter, not UKIP, who balances sharp political commentary with a passion for classical music. Wayne epitomizes tradition meeting modernity."
  ben:
    name: Ben Anderson
    display_name: Ben Anderson
    gravatar: a47c41ddcb8b4c72b9c1c79e3af68037
    email: ben.anderson@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/ben
    twitter: https://twitter.com/benandersonJG
    description: "Hailing from Clacton, Ben is a wordsmith known for his knack for humor. Infusing his articles with wit and satire, he offers a lighthearted take on events in Jaywick and beyond. Despite his penchant for jest, he's not afraid to voice his skepticism about climate change, adding a distinct perspective to his writing."
  pilgrim:
    name: Andy Pilgrim
    display_name: Andy Pilgrim
    gravatar: a47c41ddcb8b4c72b9c1c79e3af68037
    email: andrew.pilgrim@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/andy
    twitter: https://twitter.com/andyJG
    description: "Andy Pilgrim, a Clacton resident and Jaywick Gazette contributor, brings a unique perspective to the team. With a degree in gender studies, Andy lends a diverse voice to the publication. Beyond journalism, his passion lies in train spotting, where he finds solace in the rhythm of tracks and the stories they tell."
  vicky:
    name: Vicky Harris
    display_name: Vicky Harris
    gravatar: d4a2b3c73eaf1e86f44245e8320fda3d
    email: vic.harris@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/vicky
    twitter: https://twitter.com/vickyJG
    description: "Vicky Harris is a talented journalist with a sharp eye for detail. She is fascinated by all things occult and paranormal. She is also an avid collector of taxidermy animals. She has a particular fondness for stuffed owls."
  mako:
    name: Benjamin Carter
    display_name: Benajamin Carter
    gravatar: d4a2b3c73eaf1e86f44245e8320fda3d
    email: benjamin.carter@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/benjamincarter
    twitter: https://twitter.com/benjC
    description: "A retired solicitor, brings a wealth of legal expertise to his current endeavors. When not immersed in legal matters, he indulges his passion for Viking reenactment, embodying history with fervor. A lover of cardigans, he strikes a balance between classic style and comfort. Additionally, his role as a regional judge for Crufts showcases his dedication to canine excellence in the world of dog shows."
  anna:
    name: Anna White
    display_name: Anna White
    gravatar: d4a2b3c73eaf1e86489245e8320fda3d
    email: anna.white@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/annawhite
    twitter: https://twitter.com/annawh1te_
    description: "A provocative voice unafraid to tackle controversial topics with wit and humor. From her experiences as a passionate hunt saboteur to her candid exploration of societal taboos, Anna brings a unique perspective to the world of writing. Her unfiltered narratives challenge norms and invite readers to question their own beliefs, all while maintaining a distinctive and humorous style."
  emma:
    name: Emma Swaine
    display_name: Emma Swaine
    gravatar: d4a2b3c73eaf1e86489jfye8320fda3d
    email: emma.swaine@jaywickgazette.co.uk
    web: https://www.jaywickgazette.co.uk/EmmaSwaine 
    twitter: https://twitter.com/EmmaSwaine_2390
    description: "Emma, with a decade of experience in Fashion Journalism, brings her unique style to The Jaywick Gazette. Known for her fashionable hats and witty slogan tees, Emma's affection for the local community and wildlife shines through her writing. When she's not working, you can find her teeing off at Clacton Golf Club and catching up with her long-distance boyfriend, Michel, in Luxembourg."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: ""
adsense-data-ad-slot: ""

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
